server:
  port: 8090

spring:
  application:
    name: redis-pubsub

  data:
    redis:
      cluster:
        nodes:
          - 172.29.3.164:6379  # master1
          - 172.29.3.164:6380  # master2
          - 172.29.3.164:6381  # master3
          - 172.29.3.164:6382  # slave1
          - 172.29.3.164:6383  # slave2
          - 172.29.3.164:6384  # slave3
        max-redirects: 3
      timeout: 30000
      connect-timeout: 30000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1
        cluster:
          refresh:
            adaptive: true
            period: 1000
          topology-refresh-options: ALL